AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/HeredocIndentation:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
