AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/HeredocIndentation:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 120

Lint/Debugger:
  Enabled: false

Lint/SuppressedException:
  Enabled: true
  Exclude:
    - spec/*

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: true
  Exclude:
    - spec/*

Naming/MethodParameterName:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
