AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/IndentHeredoc:
  Enabled: false

Lint/SplatKeywordArguments:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 120

Metrics/MethodLength:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Rails:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false
