name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  test:

    runs-on: ${{ matrix.os }}-latest
    continue-on-error: ${{ matrix.ruby-version == 'head' }}
    strategy:
      matrix:
        os: [ubuntu, macos]
        ruby-version: ['3.3', '3.4', head]

    steps:
    - uses: actions/checkout@v2
    - name: Strip lockfile on Ruby Head to bypass mismatch bundler version
      if: matrix.ruby-version == 'head'
      run: |
        echo "Removing Gemfile.lock"
        rm -f Gemfile.lock
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: ${{ matrix.ruby-version != 'head' }} # runs 'bundle install' and caches installed gems automatically
    - name: Install dependencies for Ruby head
      if: matrix.ruby-version == 'head'
      run: bundle install
    - name: Install packages
      run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
           sudo apt update && sudo apt install -yy gdb
         elif [ "$RUNNER_OS" == "macOS" ]; then
           brew install gdb
         fi
         gdb --version
      shell: bash
    - name: Run tests
      run: bundle exec rake
      env:
        TERM: vt100 # prevent gdb output escape strings
    - name: Publish code coverage
      if: ${{ success() && runner.os == 'Linux' }}
      uses: qltysh/qlty-action/coverage@v1
      with:
        oidc: true
        files: coverage/coverage.json
